apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentp-order-gateway
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi
