apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: envoy
    chart: envoy-1.8.2
    heritage: Tiller
    release: client-edge-proxy
  name: client-edge-proxy-envoy
  selfLink: /apis/apps/v1/namespaces/default/deployments/client-edge-proxy-envoy
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: envoy
      release: client-edge-proxy
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 787ef0415040d6bfae4840be57d96bf1f6c8ed60d0bc55eda6d4e8730b44eefc
      creationTimestamp: null
      labels:
        app: envoy
        component: controller
        release: client-edge-proxy
    spec:
      containers:
      - args:
        - -l
        - $loglevel
        - -c
        - /config/envoy.yaml
        command:
        - /usr/local/bin/envoy
        image: envoyproxy/envoy:v1.11.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: admin
          timeoutSeconds: 1
        name: envoy
        ports:
        - containerPort: 9901
          name: admin
          protocol: TCP
        - containerPort: 10000
          name: n0
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: admin
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: client-edge-proxy-envoy
        name: config
status: {}
