apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":null,"generation":1,"labels":{"app":"fixmarketsimulator"},"name":"fixmarketsimulator-deployment","namespace":"default","selfLink":"/apis/apps/v1/namespaces/default/deployments/fixmarketsimulator-deployment"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"fixmarketsimulator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"fixmarketsimulator"}},"spec":{"containers":[{"env":[{"name":"FIX_FILE_STORE_PATH","value":"/usr/share/cnoms/fixmarketsimulator"}],"image":"192.168.1.200:5000/fixmarketsimulator:5","imagePullPolicy":"IfNotPresent","name":"fixmarketsimulator","ports":[{"containerPort":9876,"name":"fix-server","protocol":"TCP"},{"containerPort":8500,"name":"open-api","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/cnoms","name":"fixsim-storage"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"fixsim-storage","persistentVolumeClaim":{"claimName":"opentp-market-sim-pvc5"}}]}}},"status":{}}
  creationTimestamp: "2019-11-26T16:40:30Z"
  generation: 17
  labels:
    app: iexgsimulator
  name: iexgsimulator-deployment
  namespace: default
  resourceVersion: "1275215"
  selfLink: /apis/apps/v1/namespaces/default/deployments/fixmarketsimulator-deployment
  uid: 189ea255-beec-4dc2-91d2-73da6523b325
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iexgsimulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iexgsimulator
    spec:
      containers:
      - env:
        - name: FIX_FILE_STORE_PATH
          value: /usr/share/cnoms/iexgsimulator
        image: 192.168.1.200:5000/fixmarketsimulator:22
        imagePullPolicy: IfNotPresent
        name: iexgsimulator
        ports:
        - containerPort: 9876
          name: fix-server
          protocol: TCP
        - containerPort: 8500
          name: open-api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/cnoms
          name: fixsim-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fixsim-storage
        persistentVolumeClaim:
          claimName: opentp-nfs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-26T16:40:30Z"
    lastUpdateTime: "2020-03-27T17:26:45Z"
    message: ReplicaSet "fixmarketsimulator-deployment-7cbb95b65f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-28T11:56:50Z"
    lastUpdateTime: "2020-03-28T11:56:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
