apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2019-06-28T13:34:56Z","generation":9,"labels":{"app":"fixmarketsimulator"},"name":"fixmarketsimulator-deployment","namespace":"default","resourceVersion":"1356604","selfLink":"/apis/apps/v1/namespaces/default/deployments/fixmarketsimulator-deployment","uid":"84e92980-99a9-11e9-920c-3cd92b54ccc9"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"fixmarketsimulator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"fixmarketsimulator"}},"spec":{"containers":[{"env":[{"name":"FIX_FILE_STORE_PATH","value":"/usr/share/cnoms/fixmarketsimulator"}],"image":"192.168.1.200:5000/fixmarketsimulator:2","imagePullPolicy":"IfNotPresent","name":"fixmarketsimulator","ports":[{"containerPort":9876,"name":"fix-server","protocol":"TCP"},{"containerPort":8500,"name":"open-api","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/cnoms","name":"fixsim-storage"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"fixsim-storage","persistentVolumeClaim":{"claimName":"nfs-pv-claim"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2019-06-28T13:34:57Z","lastUpdateTime":"2019-11-02T18:25:11Z","message":"ReplicaSet \"fixmarketsimulator-deployment-5c78c569c5\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-11-04T11:57:37Z","lastUpdateTime":"2019-11-04T11:57:37Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":9,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: null
  generation: 1
  labels:
    app: fixmarketsimulator
  name: fixmarketsimulator-deployment
  selfLink: /apis/apps/v1/namespaces/default/deployments/fixmarketsimulator-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fixmarketsimulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fixmarketsimulator
    spec:
      containers:
      - env:
        - name: FIX_FILE_STORE_PATH
          value: /usr/share/cnoms/fixmarketsimulator
        image: 192.168.1.200:5000/fixmarketsimulator:5
        imagePullPolicy: IfNotPresent
        name: fixmarketsimulator
        ports:
        - containerPort: 9876
          name: fix-server
          protocol: TCP
        - containerPort: 8500
          name: open-api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/cnoms
          name: fixsim-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fixsim-storage
        persistentVolumeClaim:
          claimName: opentp-market-sim-pvc5 
status: {}
