apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2020-02-26T12:22:47Z"
  generation: 9
  labels:
    app: market-data-gateway
  name: market-data-gateway
  namespace: default
  resourceVersion: "1374060"
  selfLink: /apis/apps/v1/namespaces/default/deployments/market-data-gateway
  uid: e6317972-f4d9-483c-9f50-2c4c2089153b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: market-data-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: market-data-gateway
    spec:
      containers:
      - env:
        - name: FIX_SIM_ADDRESS
          value: iexgsimulator:50051
        - name: GATEWAY_ID
          value: fixsimgateway
        - name: STATIC_DATA_SERVICE_ADDRESS
          value: static-data-service:50551
        image: 192.168.1.200:5000/market-data-gateway:6
        imagePullPolicy: IfNotPresent
        name: market-data-gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-26T12:59:08Z"
    lastUpdateTime: "2020-03-28T13:06:48Z"
    message: ReplicaSet "market-data-gateway-57c75f76b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-01T11:41:52Z"
    lastUpdateTime: "2020-04-01T11:41:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
