apiVersion: v1
kind: PersistentVolume
metadata:
  name: opentp-execution-venue
spec:
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below 
  nfs:
    server: 192.168.1.200 # Please change this to your NFS server
    path: /mnt/k8sfolder/opentp
