apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentp-nfs 
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: opentp-nfs
  resources:
    requests:
      storage: 1Gi
