apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentp-market-sim-pvc5
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: opentp-market-sim3
  resources:
    requests:
      storage: 1Gi
