apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"17"},"creationTimestamp":"2019-11-26T16:40:30Z","generation":17,"labels":{"app":"iexgsimulator"},"name":"iexgsimulator-deployment","namespace":"default","resourceVersion":"1275215","selfLink":"/apis/apps/v1/namespaces/default/deployments/fixmarketsimulator-deployment","uid":"189ea255-beec-4dc2-91d2-73da6523b325"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"iexgsimulator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"iexgsimulator"}},"spec":{"containers":[{"env":[{"name":"FIX_FILE_STORE_PATH","value":"/usr/share/cnoms/iexgsimulator"}],"image":"192.168.1.200:5000/fixmarketsimulator:22","imagePullPolicy":"IfNotPresent","name":"iexgsimulator","ports":[{"containerPort":9876,"name":"fix-server","protocol":"TCP"},{"containerPort":8500,"name":"open-api","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/cnoms","name":"fixsim-storage"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"fixsim-storage","persistentVolumeClaim":{"claimName":"opentp-nfs"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2019-11-26T16:40:30Z","lastUpdateTime":"2020-03-27T17:26:45Z","message":"ReplicaSet \"fixmarketsimulator-deployment-7cbb95b65f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2020-03-28T11:56:50Z","lastUpdateTime":"2020-03-28T11:56:50Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":17,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-03-28T12:57:39Z"
  generation: 1
  labels:
    app: iexgsimulator
  name: iexgsimulator-deployment
  namespace: default
  resourceVersion: "1374157"
  selfLink: /apis/apps/v1/namespaces/default/deployments/iexgsimulator-deployment
  uid: 307310e1-ca69-4b0b-b2e6-ec2f3d3ed99e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iexgsimulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iexgsimulator
    spec:
      containers:
      - env:
        - name: FIX_FILE_STORE_PATH
          value: /usr/share/opentp/iexgsimulator
        image: 192.168.1.200:5000/fixmarketsimulator:22
        imagePullPolicy: IfNotPresent
        name: iexgsimulator
        ports:
        - containerPort: 9876
          name: fix-server
          protocol: TCP
        - containerPort: 8500
          name: open-api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opentp
          name: fixsim-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fixsim-storage
        persistentVolumeClaim:
          claimName: opentp-nfs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-28T12:57:39Z"
    lastUpdateTime: "2020-03-28T12:57:44Z"
    message: ReplicaSet "iexgsimulator-deployment-68b7f84f8c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-01T11:42:07Z"
    lastUpdateTime: "2020-04-01T11:42:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
