apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: market-data-service
  name: market-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: market-data-service
    spec:
      containers:
      - env:
        - name: SERVICE_ID
          value: mds
        - name: GATEWAY_ADDRESS
          value: market-data-gateway:50551
        image: ettec/opentp:market-data-service-{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: market-data-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: otpservice
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30

