apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-data-service
  name: static-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-data-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static-data-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/opentp:static-data-service-1.0.4
        imagePullPolicy: Always
        name: static-data-service

