apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-data-service
  name: static-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-data-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static-data-service
    spec:
      containers:
      - env:
        - name: DB_CONN_STRING
          value: host=opentp-postgresql.postgresql dbname=opentp sslmode=disable user=opentp
            password=password
        - name: DB_DRIVER_NAME
          value: postgres
        image: ettec/opentp:static-data-service-1.0.3
        imagePullPolicy: Always
        name: static-data-service

