apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-config-service
  name: client-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-config-service
  template:
    metadata:
      labels:
        app: client-config-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/opentp:client-config-service-{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: client-config-service

