apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: execution-venue
  name: xosr-order-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-venue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: execution-venue
        execution-venue-id: XOSR
        mic: XOSR
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/opentp:smart-router-1.0.4
        imagePullPolicy: Always
        name: execution-venue
        ports:
        - containerPort: 50551
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: otpservice
      serviceAccountName: otpservice
      terminationGracePeriodSeconds: 30
