apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: execution-venue
  name: iexg-order-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-venue
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: execution-venue
        execution-venue-id: IEXGsim
        mic: IEXG
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        env:
        - name: FIX_SOCKET_CONNECT_HOST
          value: iexgsimulator
        - name: FIX_SOCKET_CONNECT_PORT
          value: "9876"
        - name: FIX_LOG_FILE_PATH
          value: /open-trading-platform/iexg-order-gateway
        - name: FIX_FILE_STORE_PATH
          value: /open-trading-platform/iexg-order-gateway
        - name: MIC
          value: IEXG
        image: {{ .Values.dockerRepo }}fix-sim-execution-venue{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: execution-venue
        ports:
        - containerPort: 50551
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /open-trading-platform
          name: execution-venue-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: execution-venue-storage
