apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: view-service
  name: view-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: view-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/opentp:view-service-{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: view-service
