apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authorization-service
  name: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        image: ettec/opentp:authorization-service-1.0.4
        imagePullPolicy: Always
        name: authorization-service
  
