apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authorization-service
  name: authorization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:
    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
      - env:
        - name: DB_CONN_STRING
          value: host=opentp-postgresql.postgresql dbname=opentp sslmode=disable user=opentp
            password=password
        - name: DB_DRIVER_NAME
          value: postgres
        image: ettec/opentp:authorization-service-1.0.3
        imagePullPolicy: Always
        name: authorization-service
  
