apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xnas-market-data-gateway
  name: xnas-market-data-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xnas-market-data-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xnas-market-data-gateway
    spec:
      containers:
      - env:
        - name: FIX_SIM_ADDRESS
          value: xnassimulator:50051
        - name: GATEWAY_ID
          value: fixsimgateway
        - name: STATIC_DATA_SERVICE_ADDRESS
          value: static-data-service:50551
        image: ettec/opentp:market-data-gateway-fixsim-1.0.3
        imagePullPolicy: Always
        name: xnas-market-data-gateway

