apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 16443
  sessionAffinity: None
  type: ClusterIP

