apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-data-service
  name: order-data-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 50551
    protocol: TCP
    targetPort: 50551
  selector:
    app: order-data-service
  sessionAffinity: None
  type: NodePort

